---
on:
  workflow_call:

name: Azure Static Web Apps Deploy
concurrency: azure-static-web-app

permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: dist-tgz

      - name: Extract dist
        run: |
          mkdir dist_extracted
          tar -xzf dist.tgz -C dist_extracted

      - name: Build And Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          # dependabot forks the repo when making PRs, and doesn't have access
          # to secrets (like the deploy key) in actions. This allows the CI to
          # pass for dependabot PRs if the build succeeds.
          SKIP_DEPLOY_ON_MISSING_SECRETS: ${{ github.actor == 'dependabot[bot]' }}
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_GLACIER_0F640931E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "dist_extracted" # App source code path
          skip_app_build: true # Skipps app build (read from extracted tarball)
          skip_api_build: true # Skips API (functions) build step
          production_branch: "production" # all other branches are preview builds
          config_file_location: "dist_extracted"
